feature: S3C-4091-getAccount
scality/vaultclient pull request #271
Opened 2021-03-09 12:04 UTC by anurag4DSB

Vault client call for getAccount Vault API.

2021-03-09 12:04 UTC, bert-e commented
# Hello anurag4dsb,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/vaultclient/bert-e/doc/user).





*Status report is not available.*

2021-03-09 12:04 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/S3C-4091-getAccount` into
`development/7.10`
* [w/8.1/feature/S3C-4091-getAccount](https://github.com/scality/vaultclient/compare/development/8.1...w/8.1/feature/S3C-4091-getAccount) will be merged into `development/8.1` (pull request #272)
* [w/8.2/feature/S3C-4091-getAccount](https://github.com/scality/vaultclient/compare/development/8.2...w/8.2/feature/S3C-4091-getAccount) will be merged into `development/8.2` (pull request #273)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.9`
* `stabilization/7.9.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2021-03-09 12:04 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-03-09 12:08 UTC, bert-e commented
# History mismatch



Merge commit #5007e3f1faf8715487e03b2dd0d331c2685cc19c on the integration branch
`w/8.1/feature/S3C-4091-getAccount` is merging a branch which is neither the current
branch `feature/S3C-4091-getAccount` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `feature/S3C-4091-getAccount` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2021-03-09 12:10 UTC, anurag4DSB commented
/reset

2021-03-09 12:10 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2021-03-09 12:11 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/S3C-4091-getAccount` into
`development/7.10`
* [w/8.1/feature/S3C-4091-getAccount](https://github.com/scality/vaultclient/compare/development/8.1...w/8.1/feature/S3C-4091-getAccount) will be merged into `development/8.1` (pull request #274)
* [w/8.2/feature/S3C-4091-getAccount](https://github.com/scality/vaultclient/compare/development/8.2...w/8.2/feature/S3C-4091-getAccount) will be merged into `development/8.2` (pull request #275)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.9`
* `stabilization/7.9.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2021-03-09 12:11 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-03-09 18:49 UTC, bert-e commented
# History mismatch



Merge commit #c1fee60f57e20aa771597c943c86a92d94cc87ad on the integration branch
`w/8.1/feature/S3C-4091-getAccount` is merging a branch which is neither the current
branch `feature/S3C-4091-getAccount` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `feature/S3C-4091-getAccount` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2021-03-09 18:50 UTC, anurag4DSB commented
/reset

2021-03-09 18:50 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2021-03-09 18:50 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/S3C-4091-getAccount` into
`development/7.10`
* [w/8.1/feature/S3C-4091-getAccount](https://github.com/scality/vaultclient/compare/development/8.1...w/8.1/feature/S3C-4091-getAccount) will be merged into `development/8.1` (pull request #276)
* [w/8.2/feature/S3C-4091-getAccount](https://github.com/scality/vaultclient/compare/development/8.2...w/8.2/feature/S3C-4091-getAccount) will be merged into `development/8.2` (pull request #277)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.9`
* `stabilization/7.9.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2021-03-09 18:50 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-03-09 19:19 UTC, bert-e commented
# History mismatch



Merge commit #489d1de5311c471572d5b9471312ded4794c49be on the integration branch
`w/8.1/feature/S3C-4091-getAccount` is merging a branch which is neither the current
branch `feature/S3C-4091-getAccount` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `feature/S3C-4091-getAccount` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2021-03-09 19:45 UTC, anurag4DSB commented
/reset

2021-03-09 19:45 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2021-03-09 19:45 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/S3C-4091-getAccount` into
`development/7.10`
* [w/8.1/feature/S3C-4091-getAccount](https://github.com/scality/vaultclient/compare/development/8.1...w/8.1/feature/S3C-4091-getAccount) will be merged into `development/8.1` (pull request #278)
* [w/8.2/feature/S3C-4091-getAccount](https://github.com/scality/vaultclient/compare/development/8.2...w/8.2/feature/S3C-4091-getAccount) will be merged into `development/8.2` (pull request #279)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.9`
* `stabilization/7.9.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2021-03-09 19:45 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-03-09 21:50 UTC, ilkescality approved these changes

2021-03-11 05:23 UTC, saitharunthodupunuru requested changes

2021-03-11 05:23 UTC, saitharunthodupunuru commented on bin/vaultclient
> +            canonicalId: args.canonicalId || undefined,
is canonicalId going to be same as `cd_tenant_id` as we would like to `getAccount` with `cd_tenant_id` where Account has List `cd_tenant_ids`.

Other idea could be use listAccounts and filter using `cd_tenant_id`.

Which approach would be better do you think?

2021-03-11 05:23 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @saitharunthodupunuru

2021-03-11 08:38 UTC, anurag4DSB commented on bin/vaultclient
> +            canonicalId: args.canonicalId || undefined,
cd_tenant_id is out of the scope of this ticket as it has not been implemented in Account ye

2021-03-11 08:43 UTC, saitharunthodupunuru approved these changes

2021-03-11 08:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-03-11 10:52 UTC, anurag4DSB commented
/approve

2021-03-11 10:52 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.10`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.9`
* `stabilization/7.9.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-03-11 10:52 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.10`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`
* `development/7.9`
* `stabilization/7.9.0`



Please check the status of the associated issue S3C-4091.

Goodbye anurag4dsb.

2021-03-11 10:52 UTC, merged