Improvement/vltclt 33 typescript bumping
scality/vaultclient pull request #426
Opened 2023-03-29 12:37 UTC by KazToozs

- Bumps arsenal with httpagent changes
- add typsecript transpilation of IAMClient, with small changes
- bump package version

2023-03-29 12:37 UTC, bert-e commented
# Hello kaztoozs,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/vaultclient/doc/user).





*Status report is not available.*

2023-03-29 12:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-03-29 12:46 UTC, anurag4DSB requested changes
Can we have an update in vault2 with a green CI before merging?
You can use the commit hash(HEAD) of this branch, update in vault and check if the Vault2 CI is green.

Please do add the results in the description of the PR.

Edit:
1. Checkout a branch (with ticket) for Vault2
2. update this vaultclient package with the HEAD of this branch
3. check if the CI is green
4. If the CI is green, add the results to the description of this PR
5. once this PR is merged and a new version of vaultclient is released, update vault2 with the new version of vaultclient

2023-03-29 12:46 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @anurag4dsb

2023-03-31 07:23 UTC, XinLiScality approved these changes

2023-03-31 08:10 UTC, ghost approved these changes
Quick changes but otherwise LGTM

2023-03-31 08:10 UTC, ghost commented on lib/IAMClient.d.ts
> +     * @param {Number} quota - maximum quota for the account
Nit:
```suggestion
     * @param {number} quota - maximum quota for the account
```

Alternatively having the types with typescript in a jsdoc is optional, the IDE will display them correctly anyway

2023-03-31 08:10 UTC, ghost commented on lib/IAMClient.js
> +     * @param {Number} quota - maximum quota for the account
```suggestion
     * @param {number} quota - maximum quota for the account
```

2023-03-31 08:21 UTC, anurag4DSB requested changes

2023-03-31 08:21 UTC, anurag4DSB commented on lib/IAMClient.js
> +            accountName,
We need this as `name` due to OSIS.
If you want to add a type check, an alternate might be:
```suggestion
            name: accountName,
```

In Vault2 we do not support this API yet so tests will not run.

2023-03-31 11:43 UTC, anurag4DSB approved these changes

2023-03-31 11:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-03-31 11:47 UTC, KazToozs commented
/approve

2023-03-31 11:47 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.3`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `development/8.2`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2023-03-31 11:47 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.3`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `development/8.2`



Please check the status of the associated issue VLTCLT-33.

Goodbye kaztoozs.

2023-03-31 11:47 UTC, merged